name: dockerize
services:
  api:
    build: .
    container_name: dockerize-api
    entrypoint: /dockerize
    ports:
      - "8080:8080"
  bind:
    build:
      context: .
      dockerfile: bind.Dockerfile
    container_name: dockerize-bind
    volumes:
      - type: bind
        source: "./volumes/bind.txt"
        target: "/app/volumes/bind.txt"
