name: dockerize
services:
  api:
    build: .
    container_name: dockerize-api
    entrypoint: /dockerize
    ports:
      - "8080:8080"
  volume-one:
    build:
      context: .
      dockerfile: volumes.Dockerfile
    container_name: dockerize-volume-one
    volumes:
      - type: volume
        source: test-volume
        target: /app
  volume-two:
    build:
      context: .
      dockerfile: volumes.Dockerfile
    container_name: dockerize-volume-two
    volumes_from:
      - volume-one
volumes:
  test-volume:
