name: dockerize
services:
  api:
    build: .
    container_name: dockerize-api
    entrypoint: /dockerize
    networks:
      - web
    ports:
      - "8080:8080"

networks:
  web:
    driver: bridge
